name: Check CMake Installation
on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: actions/setup-node@v4
    - name: Get Yaml cpp
      run: sudo apt install libyaml-cpp-dev
    - name: Install
      run: sudo apt-get update && sudo apt-get install lcov
    - name: Install MPI
      run: sudo apt install mpich
      
    - name: Get Onika
      run: git clone --depth 1 https://github.com/Collab4exaNBody/onika.git        
    - name: Configure Onika
      run: cmake -B ${{github.workspace}}/onika/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/onika/install
      working-directory: ${{github.workspace}}/onika    
    - name: Build Onika
      run: cmake --build ${{github.workspace}}/onika/build --target install --config ${{env.BUILD_TYPE}} -j 8
      
    - name: Configure exaNBody
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -Donika_DIR=${{github.workspace}}/onika/install -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -DEXANB_BUILD_CONTRIB_MD=ON -DEXANB_BUILD_MICROSTAMP=ON -DEXANB_BUILD_CONTRIB_PI=ON -DEXANB_BUILD_MICROCOSMOS=ON -DSNAP_CPU_USE_LOCKS=ON -DSNAP_FP32_MATH=OFF
    - name: Build exaNBody
      run: cmake --build ${{github.workspace}}/build --target install --config ${{env.BUILD_TYPE}} -j 8

    - name: Run exaNBody Tests
      working-directory: ${{github.workspace}}/build
      run: ctest -C --rerun-failed --output-on-failure ${{env.BUILD_TYPE}}

    - name: Get exaStamp
      run: git clone --depth 1 https://github.com/Collab4exaNBody/exaStamp.git        
    - name: Configure exaStamp
      run: cmake -B ${{github.workspace}}/exaStamp/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DexaNBody_DIR=${{github.workspace}}/install -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/exaStamp/install
      working-directory: ${{github.workspace}}/exaStamp
    - name: Build exaStamp
      run: cmake --build ${{github.workspace}}/exaStamp/build --target install --config ${{env.BUILD_TYPE}} -j 8

    - name: Get exaDEM
      run: git clone --depth 1 https://github.com/Collab4exaNBody/exaDEM.git
    - name: Configure exaDEM
      run: cmake -B ${{github.workspace}}/exaDEM/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DexaNBody_DIR=${{github.workspace}}/install -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/exaDEM/install
      working-directory: ${{github.workspace}}/exaDEM
    - name: Build exaDEM
      run: cmake --build ${{github.workspace}}/exaDEM/build --target install --config ${{env.BUILD_TYPE}} -j 8
      
